# Generated by Django 5.2.5 on 2025-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
